data: 
  target: full
  task: NC  # NC | LP
  data_name: citeseer  # cora | citeseer | pubmed
  type: pyg
  out_channels: null
  stru_feat_principle: null  # null | concat | replace
  segment: True  # True | False
  thres: 90  # 240
  max_node_num: 100  # 250

model:
  target: SimpleGCN
  hidden_channels: 100  # according to diffusion model
  dropout: 0.5  # 0
  
train:
  patience: 100 # 50
  lr: 1e-2  # 1e-3
  wdecay: 0  # 5e-8
  epochs: 500
  initw_name: default  # default | normal | xavier | kaiming | orthogonal

sde:
  x: 
    type: VE  # VE | VP
    beta_min: 0.1
    beta_max: 1.0
    num_scales: 1  # same as augment.out_steps
  adj: 
    type: VE  # VE | VP
    beta_min: 0.1
    beta_max: 1.0
    num_scales: 1  # same as augment.out_steps

augment:
  ckpt_path: checkpoints/both/all/2_hop-max_100-Nov05-15:36:49.pth
    # checkpoints/both/all/2_hop-max_100-Nov05-15:36:49.pth
    # checkpoints/ogbn_arxiv/thres_240-max_250-Jan03-15:37:32.pth
    # checkpoints/ogbn_arxiv/thres_475-max_500-Jan03-18:57:26.pth
    # checkpoints/ogbn_arxiv/thres_950-max_1000-Jan03-16:28:49.pth
  max_node_num: 100
  batch_size: 128
  out_steps: 1
  topk: null
  start: 20 # 20
  iteration: 5 # 5
  strategy: accumulate # once | accumulate
  snr: 0.9 # 0.5
  scale_eps: 0. # 0
  perturb_ratio: 0.5 # 0.5  # 1e-2 # 1e-8
  n_steps: 1 # 1
  aug_x: True  # True | False
  aug_adj: True  # True | False
  cutoff: 0.5  # null | [0, 1)
  # infonce
  infonce: False
  n_negative: 50 # 50 # 100 # 40
  pooling: mean  # mean | sum | None