data: 
  target: seal
  task: LP  # NC | LP
  data_name: citeseer  # cora | citeseer | pubmed
  type: pyg
  num_hops: 3  # 2 | 3
  percent: 100
  use_coalesce: False
  node_label: drnl  # drnl | hop | zo | de | de+ | degree
  ratio_per_hop: 1.
  max_nodes_per_hop: null
  directed: False
  batch_size: 512

model:
  target: DGCNN
  gnn_type: gcn  # gcn | gin | sage
  norm_layer: batch_norm
    # {}_{}, first: batch | instance | layer | graph | size | pair | group
    # second: norm | size | notrack (only for batch_notrack)
  input_dim: 3703  # FEAT_DIM = {'citeseer':3703, 'pubmed': 500, 'cora': 1433}
  emb_dim: 128
  num_layers: 2
  max_z: 1000
  k: 0.6
  drop_ratio: 0.
  JK: sum
  use_feature: False
  
train:
  patience: 10
  val_int: 3
  lr: 1e-3
  wdecay: 5e-7  # 5e-7
  epochs: 500
  initw_name: default  # default | normal | xavier | kaiming | orthogonal

sde:
  x: 
    type: VE  # VE | VP
    beta_min: 0.1
    beta_max: 1.0
    num_scales: 1  # same as augment.out_steps
  adj: 
    type: VE  # VE | VP
    beta_min: 0.1
    beta_max: 1.0
    num_scales: 1  # same as augment.out_steps

augment:
  ckpt_path: checkpoints/network_repository/3_hop-max_200-Nov30-17:40:05_3200.pth
  feat_dim: 68  # same as data.max_feat_num
  n_negative: 50 # 50 # 100 # 40
  out_steps: 1
  topk: 128 # 10
  aug_batch: 1000
  start: 50 # 20
  iteration: 5 # 5
  strategy: add_accumulate # replace_once | add_once | replace_accumulate | add_accumulate
  snr: 0.9 # 0.5
  scale_eps: 0. # 0
  perturb_ratio: 0.5 # 0.5  # 1e-2 # 1e-8
  n_steps: 1 # 1
  n_jobs: 0
  pooling: mean  # mean | mean | sum | None
  aug_x: True  # True | False
  aug_adj: False  # True | False
  feat_to_compare: extract  # sum | extract
  augment_valid: False  # True | False
  augment_test: False  # True | False