data: 
  target: link_prediction

  data_name: ogbl-ppa
  # feature
  feature_flag: False
  ## segment
  segment: True
  thres: 1000
  return_list: False
  fill_zeros: False
  num_hops: 0

model:
  target: GNN

  gnn_type: gcn  # gcn | gat | sage
  act: relu
  norm: null
  hidden_channels: 256
  out_channels: 256
  num_layers: 3
  heads: 8
  dropout: 0.

predictor:
  target: mlp

  in_channels: 256
  hidden_channels: 256
  out_channels: 1
  num_layers: 3
  dropout: 0.
  
train:
  patience: 100
  eval_steps: 1
  lr: 1.0e-3
  weight_decay: 0.
  lr_schedule: False
  epochs: 10000
  batch_size: 100000  # 65536

augment:
  ckpt_path_dict:
    ## nr_clus
    0: checkpoints/network_repository/nr_clus_gnn_gt_clus0_l4_deg_lin-r.1-Feb28-13:50:20.pth
    1: checkpoints/network_repository/nr_clus_gnn_gt_clus1_l4_deg_lin-r.1-Feb28-13:51:34.pth
    3: checkpoints/network_repository/nr_clus_gnn_gt_clus3_l4_deg_lin-r.1-Feb28-13:52:37.pth
    4: checkpoints/network_repository/nr_clus_gnn_gt_clus4_l4_deg_lin-r.1-Feb28-13:53:25.pth
    6: checkpoints/network_repository/nr_clus_gnn_gt_clus6_l4_deg_lin-r.1-Feb28-13:54:15.pth
  segment_flag: True
  batch_size: 1

  sample:
    inpaint_flag: True
    thres: 0.999