data: 
  target: link_prediction

  data_name: ogbl-collab
  # feature
  feature_flag: False
  ## segment
  segment: True
  thres: 1000
  return_list: False
  fill_zeros: False
  num_hops: 0

model:
  target: NCNGCN

  hidden_channels: 256
  out_channels: 256
  num_layers: 3
  dropout: 0.3
  ln: True
  conv_fn: puregcn
  jk: True
  edrop: 0.25
  xdropout: 0.25
  taildropout: 0.05

predictor:
  target: cf

  in_channels: 128
  hidden_channels: 256
  dec: hadamard

train:
  patience: 20
  eval_steps: 1
  lr: 1.0e-3
  weight_decay: 0
  lr_schedule: False
  epochs: 10000
  batch_size: 100000
  maskinput: True

cflp:
  t: kcore
  k: 2
  selfloopT: False
  dist: euclidean
  alpha: 1.0
  beta: 1.0
  gamma: 30.0
  n_workers: 64
  neg_rate: 1
  disc_func: lin
  num_np: 1000

augment:
  ckpt_path: checkpoints/network_repository/full_nr_github_gnn_gt_l4_dnnm-50_deg_lin_self_guide-r.1-Mar29-21:15:57.pth
  segment_flag: False
  batch_size: 10

  guidance_config:
    num_epochs: 1000
    batch_size: 16
    save_flag: False

    diffusion:
      guidance_type: node_degree
      freeze_model: True

    guidance:
      target: node

      num_layers: 2
      output_dim: 1
      dropout: 0.1
      stop_grad: True  # acccording to freeze_model

  sample:
    inpaint_flag: True
    inpaint_every_step: True
    guidance_flag: True
    step_size: 0.1  # 0.1
    stability_coef: 1.0e-2  # 1.0e-2
    num_steps: 5  # 5
    thres: 0.9999
