data: 
  target: link_prediction

  data_name: ogbl-collab
  # feature
  feature_flag: False
  ## segment
  segment: True
  thres: 1000
  return_list: False
  fill_zeros: False
  num_hops: 0

model:
  target: GNN

  gnn_type: gcn  # gcn | gat | sage
  act: relu
  norm: null
  hidden_channels: 256
  out_channels: 256
  num_layers: 3
  heads: 8
  dropout: 0.

predictor:
  target: mlp

  in_channels: 256
  hidden_channels: 256
  out_channels: 1
  num_layers: 3
  dropout: 0.
  
train:
  patience: 100
  eval_steps: 1
  eval_start: 0
  lr: 1.0e-2  # 1.0e-3
  weight_decay: 0.
  lr_schedule: False
  epochs: 10000
  batch_size: 100000  # 65536

augment:
  ckpt_path: checkpoints/network_repository/full_nr_github_gnn_gt_l4_dnnm-50_deg_lin_self_guide-r.1-Mar29-21:15:57.pth
  segment_flag: False
  batch_size: 1

  guidance_config:
    num_epochs: 1000
    batch_size: 1024
    save_flag: False

    diffusion:
      guidance_type: link_pred
      freeze_model: True
    
    guidance:
      target: link

      num_layers: 3
      output_dim: 1
      dropout: 0.3
      agg: mul
      stop_grad: True  # acccording to freeze_model
      return_prob: True

  sample:
    inpaint_flag: True
    inpaint_every_step: True
    guidance_flag: True
    step_size: 0.1  # 0.1
    stability_coef: 1.0e-2  # 1.0e-2
    num_steps: 5  # 5
    thres: 0.9999
