data: 
  target: link_prediction

  data_name: ogbl-ddi
  # feature
  feature_flag: False
  ## segment
  segment: True
  thres: 1000  # 2000
  return_list: False
  fill_zeros: False
  num_hops: 0

model:
  target: GNN

  gnn_type: gcn  # gcn | gat | sage
  act: relu
  norm: null
  hidden_channels: 256
  out_channels: 256
  num_layers: 3
  heads: 8
  dropout: 0.5

predictor:
  target: mlp

  in_channels: 256
  hidden_channels: 256
  out_channels: 1
  num_layers: 3
  dropout: 0.5
  
train:
  patience: 100
  eval_steps: 1
  eval_start: 0  # 300
  lr: 1.0e-2
  weight_decay: 0.
  lr_schedule: False
  epochs: 10000
  batch_size: 100000  # 65536

augment:
  ckpt_path: checkpoints/network_repository/nr_gnn_gat-Feb06-21:31:39.pth
    # nr_gnn_gat-Feb06-21:31:39.pth
    # nr_gnn_gcn-Feb08-19:31:09.pth
    # nr_gnn_sage-Feb09-02:20:36.pth
    # nr_tgnn-Feb08-21:00:07.pth
  segment_flag: False
  batch_size: 1

  sample:
    inpaint_flag: True
    inpaint_every_step: True
    thres: 0.999