data: 
  target: link_prediction

  data_name: ogbl-collab
  # feature
  feature_flag: False
  ## segment
  segment: True
  thres: 1000
  return_list: False
  fill_zeros: False
  num_hops: 0

model:
  target: GNN

  gnn_type: gcn  # gcn | gat | sage
  act: relu
  norm: null
  hidden_channels: 256
  out_channels: 256
  num_layers: 3
  heads: 8
  dropout: 0.

predictor:
  target: mlp

  in_channels: 256
  hidden_channels: 256
  out_channels: 1
  num_layers: 3
  dropout: 0.
  
train:
  patience: 100
  eval_steps: 1
  eval_start: 0
  lr: 1.0e-2  # 1.0e-3
  weight_decay: 0.
  lr_schedule: False
  epochs: 10000
  batch_size: 100000  # 65536

augment:
  ckpt_path: checkpoints/network_repository/full_nr_github_gnn_gt_l4_dnnm-50_deg_lin_self_guide-r.1-Mar29-21:15:57.pth
  segment_flag: True
  batch_size: 4

  sample:
    inpaint_flag: True
    inpaint_every_step: True
    thres: 0.999