data: 
  target: link_prediction

  data_name: pubmed  # cora | citeseer | pubmed
  ## feature
  feature_flag: False
  feature_types:
    - node2vec
    - cn
    - ppr
  ## segment
  segment: True
  thres: 1000  # 2000
  return_list: False
  fill_zeros: False
  num_hops: 0  # 1

model:
  target: GNN

  gnn_type: gcn  # gcn | gat | sage
  act: relu
  norm: null
  hidden_channels: 128
  out_channels: 128
  num_layers: 1
  heads: 8
  dropout: 0.3

predictor:
  target: mlp

  in_channels: 128
  hidden_channels: 128
  out_channels: 1
  num_layers: 3
  dropout: 0.3
  
train:
  patience: 100  # 10
  eval_steps: 1  # 5
  lr: 1.0e-2
  weight_decay: 1.0e-4
  lr_schedule: False
  epochs: 10000
  batch_size: 1024

augment:
  ckpt_path: checkpoints/network_repository/nr_gnn_gat-Feb06-21:31:39.pth
    # nr_gnn_gat-Feb06-21:31:39.pth
    # nr_gnn_gcn-Feb08-19:31:09.pth
    # nr_gnn_sage-Feb09-02:20:36.pth
    # nr_tgnn-Feb08-21:00:07.pth
  segment_flag: False
  batch_size: 1

  guidance_config:
    num_epochs: 1000
    batch_size: 1
    save_flag: False

    diffusion:
      guidance_type: link_pred
      freeze_model: True

    guidance:
      target: link

      num_layers: 3
      output_dim: 1
      dropout: 0.3
      agg: mul
      stop_grad: True  # acccording to freeze_model
      return_prob: True

  sample:
    inpaint_flag: True
    inpaint_every_step: False
    guidance_flag: True
    step_size: 0.1  # 0.1
    stability_coef: 1.0e-2  # 1.0e-2
    num_steps: 5  # 5
    thres: 0.99
