data: 
  target: link_prediction

  data_name: pubmed  # cora | citeseer | pubmed
  ## segment
  segment: True
  thres: 2000
  return_list: False
  fill_zeros: False
  num_hops: 0

model:
  target: GNN

  gnn_type: gcn  # gcn | gat | sage
  act: relu
  norm: null
  hidden_channels: 128
  out_channels: 128
  num_layers: 1
  heads: 8
  dropout: 0.3

predictor:
  target: mlp

  in_channels: 128
  hidden_channels: 128
  out_channels: 1
  num_layers: 3
  dropout: 0.3
  
train:
  patience: 100
  eval_steps: 1
  lr: 1.0e-2
  weight_decay: 1.0e-4
  lr_schedule: False
  epochs: 10000
  batch_size: 1024

augment:
  ckpt_path: checkpoints/network_repository/full_nr_github_gnn_gt_l4_dnnm-50_deg_lin_self_guide-r.1-Mar29-21:15:57.pth
  segment_flag: True
  batch_size: 1

  guidance_config:
    num_epochs: 1000
    batch_size: 1
    save_flag: False

    diffusion:
      guidance_type: edge_cn
      freeze_model: True

    guidance:
      target: edge

      num_layers: 3
      output_dim: 1
      dropout: 0.1
      agg: concat
      stop_grad: True  # acccording to freeze_model
      return_prob: False

  sample:
    inpaint_flag: True
    inpaint_every_step: False
    guidance_flag: True
    step_size: 0.1
    stability_coef: 1.0e-2
    num_steps: 20
    thres: null
