data:
  target: generic
  ## dataset
  data_name: community
  dir_path: ./data/misc
  ## feature
  degree: True
  feature_flag: False
  ## loader
  type: pyg
  batch_size: 16  # thres ?: ? for ?G

diffusion:
  target: binary

  # noise schedule
  num_timesteps: 128
  schedule_type: linear  # linear | cosine
  # parameterization
  loss_type: vb_kl  # vb_kl | vb_ce_xt
  parametrization: x0
  # other
  sample_time_method: importance  # importance | uniform
  pi: 1.0e-12

model:
  target: TGNN  # GNN | STA | GT | TGNN

  out_channels: 2
  dim: 64
  num_heads: 8
  num_layers: 5
  dropout: 0.1
  norm: Null
  agg: concat  # concat | mul | sum

train:
  name: ego_tgnn
  seed: 10
  num_epochs: 10000 # 1000 # 5000
  save_interval: 10000 # 100 # 5000
  eval_interval: 1000 # 100 # 1000
  lr: 1.0e-3
  lr_schedule: True
  lr_decay: 0.999
  ema: 0.999
  weight_decay: 5.0e-8
  grad_norm: 1.0

sample:
  ckpt_path: checkpoints/community/comm_tgnn-Jan30-00:35:09.pth

  sample_from_empty: False
  # currently not used
  t_start: 1
  noisy_input: True
  t_sample: 0
  impaint_flag: False
  temp: 1.0
  num_sample_steps: null
  step_size: 0.1
  stability_coef: 1e-2
  num_steps: 5

# CUDA_VISIBLE_DEVICES=7 python pretrain.py --config pretrain_config/binary/comm_tgnn.yaml --prefix comm_tgnn_l4 model.num_layers=4