data:
  target: unlabeled_segments

  ## dataset
  data_name_list: 
    - network_repository
  dir_path: ./data/misc
  ## feature
  feature_types:
    - node2vec
    - cn
    - ppr
  ## segment
  segment: True
  thres: 2000
  return_list: True
  fill_zeros: False
  ## loader
  type: pyg
  batch_size: 1  # thres ?: ? for ?G

diffusion:
  target: binary

  # noise schedule
  num_timesteps: 128
  schedule_type: linear  # linear | cosine
  # parameterization
  loss_type: vb_kl  # vb_kl | vb_ce_xt
  parametrization: x0  # x0 | xt
  # other
  sample_time_method: importance  # importance | uniform
  pi: 1.0e-12

model:
  target: TGNN  # GNN | STA | GT | TGNN

  out_channels: 2
  dim: 128
  num_heads: 8
  num_layers: 5
  dropout: 0.1
  norm: Null
  agg: concat  # concat | mul | sum
  
train:
  name: ego_gnn
  seed: 10
  num_epochs: 10000 # 1000 # 5000
  save_interval: 10000 # 100 # 5000
  eval_interval: 10001 # 100 # 1000
  lr: 1.0e-3
  lr_schedule: True
  lr_decay: 0.999
  ema: 0.999
  weight_decay: 5.0e-8
  grad_norm: 1.0

sample:
  ckpt_path: checkpoints/community/comm_gnn_gcn-Jan30-00:31:05.pth
    # comm_gnn_gat-Jan30-00:53:15.pth
    # comm_gnn_gcn-Jan30-00:31:05.pth
    # comm_gnn_sage-Jan30-00:30:14.pth
    # comm_gnn_gcn_noflip-Jan30-18:05:42.pth
    # comm_gnn_gcn_noflip_nolbd-Jan30-18:08:53.pth

  sample_from_empty: False
  t_start: 1
  t_sample: 0
  temp: 1.0
  num_sample_steps: null
  # impaint
  noisy_input: True
  impaint_flag: False
  # guidance
  step_size: 0.1
  stability_coef: 1e-2
  num_steps: 5