data: 
  target: graph_prop_pred

  data_name: ogbg-moltoxcast
  add_self_loop: False
  one_hot: False
  ## loader
  batch_size: 1024

model:
  target: GINVirtualnode

  emb_dim: 300
  num_layers: 5
  drop_ratio: 0.5
  JK: last
  graph_pooling: mean
  edge_feat: False

train:
  epochs: 100
  lr: 1.0e-3
  step_size: 50
  gamma: 0.5
  patience: 100

augment:
  ckpt_path: checkpoints/network_repository/full_nr_github_gnn_gt_l4_dnnm-50_deg_lin_self_guide-r.1-Mar29-21:15:57.pth
  nodes_max: 1e5
  edges_max: 2e6
  batch_size: 1
  num_repeats: 1
  replace_flag: False
  augment_valid: False
  augment_test: False

  guidance_config:
    num_epochs: 500
    batch_size: 1024
    save_flag: False

    diffusion:
      guidance_type: graph_binary
      freeze_model: True

    guidance:
      target: graph

      num_layers: 2
      output_dim: 1
      dropout: 0.1
      stop_grad: True  # acccording to freeze_model

  sample:
    guidance_flag: True
    step_size: 0.1
    stability_coef: 1.0e-2
    num_steps: 5
    thres: null