data: 
  target: node_induced

  data_name: squirrel
  full_to_undirected: True
  sub_to_undirected: True
  subgraph_type: ego
  num_hops: 2
  ## loader
  batch_size: 128

model:
  target: GCNWithPooling

  hidden_channels: 64
  dropout: 0.5
  subset: True
  subset_type: top
  k: 1

train:
  epochs: 50
  lr: 1.0e-2
  wdecay1: 5.0e-4
  wdecay2: 0.
  step_size: 50
  gamma: 0.5
  patience: 100

augment:
  ckpt_path: checkpoints/network_repository/full_nr_gnn_gt_l4_dnnm-0_deg_lin_self_guide-r.1-Mar08-02:01:14.pth
  nodes_max: 1e5
  edges_max: 2e6
  batch_size: 1
  num_repeats: 1
  replace_flag: False
  augment_valid: False
  augment_test: False

  guidance_config:
    num_epochs: 500
    batch_size: 200
    save_flag: False

    diffusion:
      guidance_type: graph_class
      freeze_model: True

    guidance:
      target: graph

      num_layers: 2
      output_dim: 1
      dropout: 0.1
      stop_grad: True  # acccording to freeze_model

  sample:
    guidance_flag: True
    step_size: 0.1
    stability_coef: 1.0e-2
    num_steps: 5
    thres: null